# @package _global_

# specify here default training configuration
# Each value yaml file will be searched in the key config folder, e.g. configs/model/unet_resnet.yaml (the yaml ending is optional)
# NOTE: Configs can only override stuff that appears *before it* in the defaults list.
defaults:
  - _self_
  - trainer: trainer.yaml
  - model: unet_resnet.yaml  # unet.yaml
  - diffusion: dyffusion.yaml  # null
  - datamodule: imerg_precipitation.yaml
  - module: forecasting_multi_horizon_dyffusion.yaml
  # - module: interpolation.yaml
  - callbacks: callbacks.yaml
  - logger: csv_logger.yaml
  
# Note: hydra.runtime.cwd points to the original working dir.
# ${hydra:runtime.cwd} is the path to original working directory
# hydra hijacks working directory by changing it to the new log directory so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ./results       # ${hydra:runtime.cwd}  # oc.env allows to get environment variable
ckpt_dir: ${work_dir}/checkpoints/
log_dir: ${work_dir}/logs/

# pretty print config at the start of the run using Rich library (requires Rich to be installed!)
print_config: True
# disable python warnings if they annoy you
ignore_warnings: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on metric specified in checkpoint callback
test_after_training: False
# Checkpoint path to be loaded from wandb cloud (see files tab of run page) or locally (use absolute path)
ckpt_path: null
verbose: True

# Global seed for random number generators in pytorch, numpy and python.random for reproducibility
# Note: It does *not* apply to the data split, which is done based on the random seed specified in the datamodule
seed: 11
torch_matmul_precision: "high"   # choose from "highest", "high", "medium" for speed/precision tradeoff

# name of the run - good to use along with experiment_types mode
name: 'ImergPrecipitation-${module.experiment_type}-MH${datamodule.horizon}-BS${datamodule.batch_size}-DYffusion'

name_suffix: 'test'   # will be appended to the name
suffix: null          # will be appended after all hyperparameters IDs and other suffixes